name: environmental
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6,<3.10
  - pip
  - numpy>1.16
  - scipy
  - matplotlib
  - pytest
  - setuptools>=26
  - autopep8
  - pandas
  - scikit-learn
  - seaborn
  - jupyter
  - jupyterlab
  - pytest
  - pytz
  - bs4
  - datetime
  

